### ISSUE TITLE
Pinned cookbook dependency versions hang Librarian

### ISSUE THREAD

**Issue by hectcastro** [basho/riak-chef-cookbook#127]
If cookbook dependency version constraints use `~>`, it causes [Librarian](https://github.com/applicationsonline/librarian-chef) to eat 100% CPU and hang.

This issue was split out of https://github.com/basho/riak-chef-cookbook/pull/125.

/cc @zquestz

**Comment by cheeseplus** [comment]
Berkshelf is not only officially blessed by Chef but given adoption amongst Chef users I'm closing as wont-fix until/unless someone else raises the issue again.
