### ISSUE TITLE
Automatic Deep Merging of Attributes causing issues

### ISSUE THREAD

**Issue by janpieper** [basho/riak-chef-cookbook#51]
I am wondering how to get rid of the default user for riak_control... I've added `riak_control` with one user (name: `foo`, password: `bar`) but after running `chef-client` there are two users (default user + my new user) in `userlist`.

#### [riak-chef-cookbook] /attributes/default.rb

````ruby
...
default['riak']['config']['riak_control']['userlist'] = [
  ["user".to_erl_string,"pass".to_erl_string].to_erl_tuple
]the 
...
````

#### [chef-server] /roles/riak.json

````json
{
  ...
  "override_attributes": {
    "riak": {
      "config": {
        "riak_control": {
          "userlist": [
            ["__tuple", "foo", "bar"]
          ]
        }
      }
    }
  }
  ...
}
````

#### [server] /etc/riak/app.config

````erlang
[
  ...
  {riak_control, [
    {userlist, [
      {"user", "pass"}, % <--- ???
      {"foo", "bar"}
    ]}
  ]}
  ...
].
````

**Comment by cheeseplus** [comment]
Closing this as 2.0 brought the new configuration format but feel free to raise another issue if extracting the port is still a problem.
